---
fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    sudo: https://github.com/saz/puppet-sudo.git
    systemd: https://github.com/voxpupuli/puppet-systemd.git
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
